name: Backend Tests

on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches:
      - '**'
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-local-path: "/tmp/uv-cache"
          python-version: '3.13'

      - name: Install dependencies
        run: uv sync

      - name: Run Pytest
        run: uv run pytest
